nelmio_api_doc:
    documentation:
        info:
            title: Fruits and Vegetables
            description: Fruits and Vegetables
            version: 1.0.0
        tags:
            - name: "Fruits"
              description: "Endpoints related to fruits"
            - name: "Vegetables"
              description: "Endpoints related to vegetables"
        components:
            schemas:
                Fruit:
                    type: "object"
                    properties:
                        id:
                            type: "integer"
                        name:
                            type: "string"
                        grams:
                            type: "integer"
                    required:
                        - id
                        - name
                        - grams
                Vegetable:
                    type: "object"
                    properties:
                        id:
                            type: "integer"
                        name:
                            type: "string"
                        grams:
                            type: "integer"
                    required:
                        - id
                        - name
                        - grams
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc